IMPORTANT: USING react-native-permission@2.0.10 (like master) DO NOT use the latest version 2.1.3 WILL PRODUCE ERROR TypeError: RNPermissions.isAvailable is not a function. DO NOT use requestMultiple because it is still unstable and more likely to cause eerror